// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMQJIWkVpRsD2WH5YKBty8hm7B_NQhgk',
    appId: '1:176062135688:web:f4da7c5899a9b0342bce3d',
    messagingSenderId: '176062135688',
    projectId: 'panic-attack-app',
    authDomain: 'panic-attack-app.firebaseapp.com',
    storageBucket: 'panic-attack-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtXvnMO4q6ukIc0Q85L6FLa_UwQlYN9E0',
    appId: '1:176062135688:android:2198a27ac0bd838c2bce3d',
    messagingSenderId: '176062135688',
    projectId: 'panic-attack-app',
    storageBucket: 'panic-attack-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITKGjM6sVF1bEhJzoVrnLanP6G85DXrA',
    appId: '1:176062135688:ios:cca3accb8d9523342bce3d',
    messagingSenderId: '176062135688',
    projectId: 'panic-attack-app',
    storageBucket: 'panic-attack-app.appspot.com',
    iosBundleId: 'com.example.panicattackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAITKGjM6sVF1bEhJzoVrnLanP6G85DXrA',
    appId: '1:176062135688:ios:04dc55ff55fee98a2bce3d',
    messagingSenderId: '176062135688',
    projectId: 'panic-attack-app',
    storageBucket: 'panic-attack-app.appspot.com',
    iosBundleId: 'com.example.panicattackApp.RunnerTests',
  );
}
